/** Generated by scripts/seed-from-student-list.ts — do not edit. */
export const REGISTER_MAX_STUDENT_NUMBER = 456;
export const REGISTER_NEXT_STUDENT_NUMBER = 457;
export const REGISTER_SOURCE = "public\\student\\KIGALI SAFETY ACADEMY STUDENTS LIST.docx";
